networks:
  dev:


services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:8080"
      # - "443:443"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - backend
      - frontend
      - db
    networks:
      - dev
  backend:
    build:
      context: ./backend
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - dev
  frontend:
    build:
      context: ./mern-blog-frontend-master
    networks:
      - dev
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: post205077
      POSTGRES_DB: db_fullstack_junior
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - "5432:5432"
    tty: true
    stdin_open: true
    networks:
      - dev

volumes:
  pgdata:
    driver: local
